// Draw fish and frames on (emulated) Xtensa and print hashes of the exact
// results, for compare.mjs to check against the JavaScript.
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "fishdraw.h"
#include "fishfodder.h"
#include "names.h" // generated by compare.mjs

static uint64_t h64;
static void mix(const void *p, size_t n) {
  const uint8_t *b = p;
  for (size_t i = 0; i < n; i++) h64 = (h64 ^ b[i]) * 0x100000001b3ull;
}

int main(void) {
  for (size_t i = 0; i < sizeof NAMES / sizeof *NAMES; i++) {
    fd_drawing d;
    if (fishdraw(NAMES[i], &d)) { printf("fish %u ERROR\n", (unsigned)i); continue; }
    h64 = 0xcbf29ce484222325ull;
    for (int l = 0; l < d.n; l++) {
      int32_t n = d.lines[l].n;
      mix(&n, 4);
      for (int j = 0; j < n; j++) mix(&d.lines[l].points[j], 16);
    }
    printf("fish %u %08lx%08lx %u\n", (unsigned)i, (unsigned long)(h64 >> 32), (unsigned long)(uint32_t)h64,
           (unsigned)d.peak_bytes);
    fishdraw_free(&d);
  }
  static const struct { ff_time t; int w, h, rot, h12, hourly; ff_sky sky; double hi, lo; } F[] = {
    {{2026, 10, 3, 14, 5, 6}, 800, 480, 0, 0, 0, FF_PARTLY, 19, 11},
    {{2026, 1, 31, 0, 59, 6}, 800, 480, 90, 1, 1, FF_RAIN, -0.4, -12.6},
    {{2026, 7, 4, 12, 30, 6}, 400, 300, 0, 1, 0, FF_SNOW, 1, -4},
    {{2026, 3, 9, 23, 1, 1}, 296, 128, 270, 0, 0, FF_STORM, 24, 17},
  };
  for (size_t i = 0; i < sizeof F / sizeof *F; i++) {
    ff_weather w = {F[i].sky, F[i].hi, F[i].lo};
    ff_options o = {F[i].w, F[i].h, F[i].rot, F[i].h12, F[i].hourly, NULL, &w, NULL};
    ff_bitmap b;
    if (ff_render(&F[i].t, &o, &b, NULL)) { printf("frame %u ERROR\n", (unsigned)i); continue; }
    h64 = 0xcbf29ce484222325ull;
    mix(b.pixels, (size_t)b.width * b.height);
    printf("frame %u %08lx%08lx\n", (unsigned)i, (unsigned long)(h64 >> 32), (unsigned long)(uint32_t)h64);
    ff_bitmap_free(&b);
  }
  return 0;
}
