// Generate c/fishfodder_data.h from the JavaScript sources, so the C port
// uses exactly the same word lists and fonts:  node scripts/gen-c-data.js
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { WORDS } from '../src/names.js';
import { ROMAN_SIMPLEX, ROMAN_DUPLEX } from '../src/hershey-data.js';

const out = fileURLToPath(new URL('../c/fishfodder_data.h', import.meta.url));
const str = (s) => JSON.stringify(s); // ASCII only, so JSON escaping is valid C
const list = (name, arr) => {
  for (const s of arr) if (!/^[\x20-\x7e]*$/.test(s)) throw new Error(`non-ASCII in ${name}: ${s}`);
  return `static const char *const ${name}[] = {\n${arr.map((s) => `    ${str(s)},`).join('\n')}\n};\n`;
};

let h = `// Generated by scripts/gen-c-data.js from src/names.js and src/hershey-data.js.
// Don't edit; regenerate.
#ifndef FISHFODDER_DATA_H
#define FISHFODDER_DATA_H

#define COUNT(a) ((int)(sizeof(a) / sizeof((a)[0])))

`;
for (const [name, arr] of Object.entries(WORDS)) {
  if (name === 'NOTES') continue;
  h += list(name, arr) + '\n';
}
const fields = Object.keys(WORDS.NOTES);
h += list('NOTE_FIELDS', fields) + '\n';
fields.forEach((f, i) => { h += list(`NOTE_VALUES_${i}`, WORDS.NOTES[f]) + '\n'; });
h += `static const char *const *const NOTE_VALUES[] = {${fields.map((_, i) => `NOTE_VALUES_${i}`).join(', ')}};\n`;
h += `static const int NOTE_COUNTS[] = {${fields.map((_, i) => `COUNT(NOTE_VALUES_${i})`).join(', ')}};\n\n`;
h += '// Hershey stroke fonts, ASCII 32..126 (see src/hershey-data.js for credits).\n';
h += list('ROMAN_SIMPLEX', ROMAN_SIMPLEX) + '\n' + list('ROMAN_DUPLEX', ROMAN_DUPLEX) + '\n#endif\n';
writeFileSync(out, h);
console.log(`wrote ${out}`);
